name: Deploy to EC2

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            git clone https://github.com/dakotadavis58/dev-portfolio.git devfolio || (cd devfolio && git pull)
            cd devfolio
            npm ci
            npm run build
            pm2 startOrReload pm2.config.js --update-env
          '
          rm -f private_key
